### ISSUE TITLE
react-scripts dependency

### ISSUE THREAD

**Issue by annitya** [cognitedata/react-auth-wrapper#15]
This dependency introduces a vulnerability into our code base:
![image](https://user-images.githubusercontent.com/727305/190435145-0b2f1097-8274-4e0b-9297-2ee13fb5060b.png)
Perhaps it could be removed all together, or does the auth-provider need it to run?

**Comment by cognite-ornellas** [comment]
Hey, we are taking a look at it. Will fix it soon.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/39047273/204642633-7c643937-9115-4f6f-9ad4-1b2b457bf4e4.png)
Look what you made me do :P

On a more serious note, any progress? :)
